import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import Header from '@/components/Header';
import { Poppins } from 'next/font/google';
import { Toast, Toaster } from 'react-hot-toast';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'MakanNow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className='font-poppins '>
        <Providers>
          <Toaster />
          <Header />
          { children }
        </Providers>
      </body>
    </html>
  )
}
